services:
  db:
    image: postgres:16-alpine
    container_name: incident-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: incident_db
      POSTGRES_USER: incident_user
      POSTGRES_PASSWORD: incident_password
    ports:
      - "5432:5432"
    volumes:
      - incident_pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  incident_pgdata:
